nilead_pricing:
  driver: doctrine/orm

nilead_payments:
  driver: doctrine/orm

nilead_product:
  driver: doctrine/orm	  

nilead_shipments:
    driver: doctrine/orm
    classes:
        shipment:
            model: Nilead\CoreBundle\Entity\Shipment
        shipment_item:
            model: Nilead\CoreBundle\Entity\ShipmentItem
        picklist_item:
            model: Nilead\CoreBundle\Entity\PicklistItem

nilead_contact:
    driver: doctrine/orm
    classes:
        organization:
            model: Nilead\CoreBundle\Entity\Organization
        party:
            model: Nilead\CoreBundle\Entity\Party
        party_type:
            model: Nilead\CoreBundle\Entity\PartyType

nilead_inventory:
    driver: doctrine/orm
    classes:
        inventory_item:
            model: Nilead\CoreBundle\Entity\InventoryItem
        inventory_adjustment:
            model: Nilead\CoreBundle\Entity\InventoryAdjustment

sylius_resource:
    resources:
        nilead.user:
            driver: doctrine/orm
            classes:
                model: Nilead\CoreBundle\Entity\User

parameters:
    nilead_shipments.manager.shipment.default.class:      Nilead\CoreBundle\Manager\ShipmentManager