parameters:
    kernel.config_dir: '%kernel.root_dir%/config'
    plugins.root_dir: '%kernel.root_dir%/plugins'
    store.enable_ssl: false
    store.frontend.templates_dir: '%kernel.root_dir%/frontend/templates'
    store.frontend.current_template: classic
    store.backend.templates_dir: '%kernel.root_dir%/backend/templates'
    store.backend.current_template: template_default
    store.root_dir: '%kernel.root_dir%/../web'
    web.dir: '%kernel.root_dir%/../web'
    web.relative_dir: ''
    web.cache_dir: '%web.dir%/cache'
    web.images_dir: '%web.dir%/images'

    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: zeni
    database_user: root
    database_password: null
    database_path: null

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret: 3255ebb771cac20afc031da3073883fe64aefd80

    liip_theme.themes: ['shopper', 'bootstrap']
    liip_theme.active_theme: 'shopper'
    liip_theme.autodetect_theme: true
    liip_theme.cookie:
    name: fsdf
    lifetime: 7200
    path: /
    domain: localhost
    secure: false
    http_only: false


  # Nilead Breadcrumbs
  #
  # Your can find full list resolvers with description in:
  # NileadBreadcrumbsBundle:Resources/config:resolver.xml
    breadcrumbs:
        nilead.frontend.product.info:
            - title: nilead.breadcrumbs.home
              url: 'nilead.frontend.index'
            - '%nilead.resolver.categories_by_product%'
            - '%nilead.resolver.product%'

        nilead.frontend.product.listing_by_category:
            - title: nilead.breadcrumbs.home
              url: 'nilead.frontend.index'
            - '%nilead.breadcrumbs.categories_by_category%'

        nilead.frontend.cart.summary:
            - title: nilead.breadcrumbs.home
              url: 'nilead.frontend.index'
            - title: nilead.breadcrumbs.shopping_cart
              url: 'nilead.frontend.cart.summary'
