fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

# fos_user_register:
#     resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#     prefix: /register

# fos_user_resetting:
#     resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#     prefix: /resetting

# fos_user_change_password:
#     resource: "@NileadWebBundle/Resources/config/routing/common/change_password.xml"
#     prefix: /account

nilead:
    resource: "@NileadWebBundle/Resources/config/routing/main.xml"
    prefix: /

nilead_user_register:
    resource: "@NileadWebBundle/Resources/config/routing/common/registration.xml"
    prefix: /register

_imagine:
    resource: .
    type: imagine